<?php
return [
    'countries' => [
        "Abkhazia",
        "Afghanistan",
        "Aland Islands",
        "Albania",
        "Algeria",
        "American Samoa",
        "Andorra",
        "Angola",
        "Anguilla",
        "Antarctica",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Aruba",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bermuda",
        "Bhutan",
        "Bolivia",
        "Bonaire",
        "Bosnia and Herzegovina",
        "Botswana",
        "Bouvet Island",
        "Brazil",
        "British Indian Ocean",
        "Brunei Darussalam",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Canary Islands",
        "Cape Verde",
        "Cayman Islands",
        "Central African Republic",
        "Chad",
        "Channel Islands",
        "Chile",
        "China",
        "Christmas Island",
        "Cocos Island",
        "Colombia",
        "Comoros",
        "Congo",
        "Cook Islands",
        "Costa Rica",
        "Cōte dIvoire",
        "Croatia",
        "Cuba",
        "Curacao",
        "Cyprus",
        "Czech Republic",
        "Democratic Republic of the Congo",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "East Timor",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Eswatini",
        "Ethiopia",
        "Falkland Islands",
        "Faroe Islands",
        "Federated States of Micronesia",
        "Fiji",
        "Finland",
        "France",
        "French Guiana",
        "French Polynesia",
        "French Southern Territories",
        "Gabon",
        "Georgia",
        "Germany",
        "Ghana",
        "Gibraltar",
        "Greece",
        "Greenland",
        "Grenada",
        "Guadeloupe",
        "Guam",
        "Guatemala",
        "Guernsey",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Hawaii",
        "Heard Island and McDonald Islands",
        "Honduras",
        "Hong Kong",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Ireland",
        "Isle of Man",
        "Israel",
        "Italy",
        "Ivory Coast",
        "Jamaica",
        "Japan",
        "Jersey",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Kosovo",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macau",
        "Macedonia",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Martinique",
        "Mauritania",
        "Mauritius",
        "Mayotte",
        "Mexico",
        "Midway Islands",
        "Moldova",
        "Monaco",
        "Mongolia",
        "Montenegro",
        "Montserrat",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Nagorno-Karabakh",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherland Antilles",
        "Netherlands",
        "Nevis",
        "New Caledonia",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Niue",
        "Norfolk Island",
        "North Korea",
        "Northern Cyprus",
        "Northern Mariana Islands",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Palestine",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Pitcairn Islands",
        "Poland",
        "Portugal",
        "Puerto Rico",
        "Qatar",
        "Reunion",
        "Romania",
        "Russian Federation",
        "Rwanda",
        "Saint Barthelemy",
        "Saint Eustatius",
        "Saint Helena",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Martin",
        "Saint Pierre and Miquelon",
        "Saint Vincent and the Grenadines",
        "Saipan",
        "Samoa",
        "Samoa American",
        "San Marino",
        "Sāo Tomė and Prīncipe",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "Somaliland",
        "South Africa",
        "South Korea",
        "South Ossetia",
        "South Sudan",
        "Spain",
        "Sri Lanka",
        "Sudan",
        "Suriname",
        "Svalbard and Jan Mayen",
        "Swaziland",
        "Sweden",
        "Switzerland",
        "Syria",
        "Tahiti",
        "Taiwan",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "The Bahamas",
        "The Gambia",
        "Timor-Leste",
        "Togo",
        "Tokelau",
        "Tonga",
        "Transnistria",
        "Trinidad and Tobago",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Turks and Caicos Islands",
        "Tuvalu",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "United States Minor Outlying Islands",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Vatican City",
        "Venezuela",
        "Vietnam",
        "Virgin Islands (Brit)",
        "Virgin Islands (USA)",
        "Wake Island",
        "Wallis and Futuna",
        "Western Sahara",
        "Yemen",
        "Zaire",
        "Zambia",
        "Zimbabwe"
    ],
    'levels_of_study' => [
        "Postgraduate",
        "Undergraduate",
        "Foundation",
        "Pre-Sessional",
        "English Language",
        "Pre-Masters",
        "Research",
        "Certificate",
        "Online",
        "Secondary school",
        "Higher secondary",
        "High school",
        "Diploma",
    ],
    'disciplines' => [
       "Accounting and Finance",
        "Aerospace and Manufacturing Engineering",
        "Agriculture, Forestry and Food",
        "American Studies",
        "Anthropology and Archaeology",
        "Architecture, Building and Planning",
        "Art and Design",
        "Biological Sciences",
        "Business and Management",
        "Chemical Engineering",
        "Chemistry",
        "Civil Engineering",
        "Communication and Media Studies",
        "Computer Science and IT",
        "Dentistry",
        "Earth and Marine Sciences",
        "Economics",
        "Education",
        "Electrical and Electronic Engineering",
        "Energy Engineering",
        "Engineering - General",
        "English Language and Literature",
        "Environmental Sciences",
        "Film, Theatre and Performing Arts",
        "Food Science and Nutrition",
        "Geography",
        "Health Professions and Related Clinical Sciences",
        "History",
        "Hospitality, Leisure, Recreation and Tourism",
        "Humanities - General",
        "Law",
        "Linguistics and Classics",
        "Mathematics and Statistics",
        "Mechanical Engineering",
        "Medicine and Surgery",
        "Music, Dance and Performing Arts",
        "Nursing",
        "Pharmacy and Pharmacology",
        "Philosophy and Religious Studies",
        "Physics and Astronomy",
        "Political Science and International Relations",
        "Psychology",
        "Public Health, Health Services and Allied Professions",
        "Social Work and Social Policy",
        "Sociology and Cultural Studies",
        "Veterinary Science"
    ]
];